// ═══════════════════════════════════════════════════════════════
// iTabs Quotes Engine v1.1
// Config-driven interactive quote estimator
// https://github.com/boilermaker-innovator/itabs-quotes
//
// DO NOT EDIT THIS FILE PER CLIENT.
// All customisation lives in the config file.
// ═══════════════════════════════════════════════════════════════

(function () {
  const C = window.WIDGET_CONFIG;
  if (!C) { console.error('iTabs Quotes: WIDGET_CONFIG not found.'); return; }

  // ── STATE ──────────────────────────────────────────────
  const state = {
    answers: {},
    sliders: {},
    toggles: {},
    openSection: null,
    completedSections: new Set(),
  };

  // ── BOOT ───────────────────────────────────────────────
  function boot() {
    injectFonts();
    injectCSS();
    applyBranding();
    initDefaults();
    render();
    setTimeout(() => toggleSection(0), 300);
  }

  function injectFonts() {
    if (C.branding.googleFontsUrl) {
      const pre = document.createElement('link');
      pre.rel = 'preconnect'; pre.href = 'https://fonts.googleapis.com';
      document.head.prepend(pre);
      const link = document.createElement('link');
      link.rel = 'stylesheet'; link.href = C.branding.googleFontsUrl;
      document.head.appendChild(link);
    }
    document.title = C.header.headline + ' | ' + C.business.name;
  }

  function applyBranding() {
    const b = C.branding; const r = document.documentElement.style;
    r.setProperty('--bg-main', b.backgroundColor); r.setProperty('--bg-card', b.cardBackground);
    r.setProperty('--bg-hover', b.hoverBackground); r.setProperty('--bg-dark', b.darkBackground);
    r.setProperty('--border', b.borderColor); r.setProperty('--brand-primary', b.primaryColor);
    r.setProperty('--brand-secondary', b.secondaryColor); r.setProperty('--brand-glow', hexToGlow(b.primaryColor));
    r.setProperty('--text-primary', b.textColor); r.setProperty('--text-secondary', b.mutedText);
    r.setProperty('--text-muted', b.dimText); r.setProperty('--accent-green', b.successColor);
    r.setProperty('--accent-red', b.errorColor); r.setProperty('--accent-blue', b.infoColor);
    r.setProperty('--font-main', b.fontFamily); r.setProperty('--font-mono', b.monoFont);
    r.setProperty('--radius', b.borderRadius);
  }

  function hexToGlow(hex) {
    const r = parseInt(hex.slice(1,3),16), g = parseInt(hex.slice(3,5),16), b = parseInt(hex.slice(5,7),16);
    return `rgba(${r},${g},${b},0.15)`;
  }

  function initDefaults() {
    C.steps.forEach(step => {
      if (step.input.type === 'slider_group') {
        step.input.sliders.forEach(s => {
          const raw = s.default;
          if (s.valueMap) {
            const mapped = s.valueMap.find(v => v.value === raw);
            state.sliders[s.id] = { raw, numeric: mapped ? mapped.numericValue : raw, label: mapped ? mapped.label : raw + (s.unit || '') };
          } else {
            state.sliders[s.id] = { raw, numeric: raw, label: raw + (s.unit || '') };
          }
        });
      }
      if (step.input.type === 'toggle_group') {
        step.input.toggles.forEach(t => { state.toggles[t.id] = false; });
      }
    });
  }

  // ── RENDER ─────────────────────────────────────────────
  function render() {
    const app = document.getElementById('app');
    if (!app) { console.error('iTabs Quotes: #app element not found.'); return; }
    let html = renderHeader();
    if (C.socialProof && C.socialProof.enabled) html += renderSocialProof();
    const totalSections = C.steps.length + (C.estimate ? 1 : 0) + (C.leadCapture && C.leadCapture.enabled ? 1 : 0);
    html += `<div class="progress-label"><span>Your quote</span><span id="progressText">0 of ${totalSections}</span></div><div class="progress-bar"><div class="progress-fill" id="progressFill"></div></div>`;
    C.steps.forEach((step, i) => { html += renderSection(step, i); });
    if (C.estimate) html += renderEstimateSection(C.steps.length);
    if (C.leadCapture && C.leadCapture.enabled) html += renderLeadSection(C.steps.length + (C.estimate ? 1 : 0));
    if (C.footer && C.footer.showPoweredBy) html += `<div class="powered-by">Powered by <a href="${C.footer.poweredByUrl}" target="_blank">iTabs</a> · Interactive tools that convert</div>`;
    app.innerHTML = html;
  }

  function renderHeader() {
    const h = C.header;
    return `<div class="header"><div class="header-icon">${h.icon}</div><h1>${h.headline}</h1><p>${h.subtitle}</p>${h.badge ? `<span class="badge-line">${h.badge}</span>` : ''}</div>`;
  }

  function renderSocialProof() {
    const sp = C.socialProof;
    return `<div class="social-proof"><span class="sp-stars">${'★'.repeat(Math.floor(sp.rating))}</span><span class="sp-rating">${sp.rating} from ${sp.reviewCount} reviews</span>${sp.badges.map(b => `<span class="sp-badge">${b}</span>`).join('')}</div>`;
  }

  function renderSection(step, index) {
    const sid = `section-${index}`;
    const completed = state.completedSections.has(sid) ? ' completed' : '';
    const isOpen = state.openSection === sid;
    const preview = getPreview(step);
    const inputTabLabel = step.input.type === 'toggle_group' ? 'Add Extras' : step.input.type === 'slider_group' ? 'Set Size' : 'Choose';
    const hintTabs = step.hints || [];
    let ch = '';
    if (hintTabs.length > 0) {
      ch += `<div class="tabs"><button class="tab active" onclick="iTabs.showTab(this,'${sid}-input')">${inputTabLabel}</button>`;
      hintTabs.forEach((h, hi) => { ch += `<button class="tab" onclick="iTabs.showTab(this,'${sid}-hint-${hi}')">${h.tabLabel}</button>`; });
      ch += `</div>`;
    }
    ch += `<div class="tab-panel show" id="${sid}-input">${renderInput(step, sid)}`;
    if (step.warnings) step.warnings.forEach(w => {
      ch += `<div class="warning-card" id="${sid}-warning-${w.condition.replace(/[^a-z0-9]/gi,'')}" style="display:none;"><div class="warning-title">${w.icon} ${w.title}</div><p>${w.text}</p></div>`;
    });
    ch += `</div>`;
    hintTabs.forEach((hint, hi) => { ch += `<div class="tab-panel" id="${sid}-hint-${hi}">${renderHint(hint)}</div>`; });
    return `<div class="itab-section${completed}" id="${sid}"><div class="itab-header" onclick="iTabs.toggleSection(${index})"><div class="itab-title"><span class="itab-number">${index + 1}</span><div><div class="itab-name">${step.title}</div><div class="itab-preview" id="${sid}-preview">${preview}</div></div></div><button class="i-button" id="${sid}-btn">i</button></div><div class="itab-content${isOpen ? ' show' : ''}" id="${sid}-content">${ch}</div></div>`;
  }

  function renderEstimateSection(index) {
    const sid = `section-${index}`;
    const est = C.estimate;
    const isOpen = state.openSection === sid;
    const completed = state.completedSections.has(sid) ? ' completed' : '';
    let hintsHtml = '';
    if (est.hints) est.hints.forEach(h => { hintsHtml += renderHintItem(h); });
    return `<div class="itab-section${completed}" id="${sid}"><div class="itab-header" onclick="iTabs.toggleSection(${index})"><div class="itab-title"><span class="itab-number">${index + 1}</span><div><div class="itab-name">${est.title}</div><div class="itab-preview" id="${sid}-preview">${est.preview}</div></div></div><button class="i-button" id="${sid}-btn">i</button></div><div class="itab-content${isOpen ? ' show' : ''}" id="${sid}-content"><div class="estimate-box"><div class="est-label">Estimated range</div><div class="est-range" id="estRange">—</div><div class="est-note" id="estNote">Complete the sections above to see your estimate</div><div class="estimate-breakdown" id="estBreakdown"></div></div>${hintsHtml}</div></div>`;
  }

  function renderLeadSection(index) {
    const sid = `section-${index}`;
    const lc = C.leadCapture;
    const isOpen = state.openSection === sid;
    const completed = state.completedSections.has(sid) ? ' completed' : '';
    let fieldsHtml = '';
    lc.fields.forEach(f => {
      const req = f.required ? ' *' : '';
      fieldsHtml += f.type === 'textarea'
        ? `<div class="form-group"><label>${f.label}${req}</label><textarea id="form-${f.id}" placeholder="${f.placeholder}"></textarea></div>`
        : `<div class="form-group"><label>${f.label}${req}</label><input type="${f.type}" id="form-${f.id}" placeholder="${f.placeholder}"></div>`;
    });
    return `<div class="itab-section${completed}" id="${sid}"><div class="itab-header" onclick="iTabs.toggleSection(${index})"><div class="itab-title"><span class="itab-number">${index + 1}</span><div><div class="itab-name">${lc.title}</div><div class="itab-preview" id="${sid}-preview">${lc.preview}</div></div></div><button class="i-button" id="${sid}-btn">i</button></div><div class="itab-content${isOpen ? ' show' : ''}" id="${sid}-content"><div id="leadFormContainer"><p style="color:var(--text-secondary);font-size:0.9rem;margin-bottom:16px;">${lc.subheading}</p>${lc.showSummary ? `<div class="summary-box"><div class="summary-label">Your specs</div><div class="summary-content" id="quoteSummary">Select your options above first</div></div>` : ''}${fieldsHtml}<button class="submit-btn" id="submitBtn" onclick="iTabs.submitLead()">${lc.submitText}</button>${lc.submitNote ? `<div style="text-align:center;margin-top:12px;font-size:0.75rem;color:var(--text-muted)">${lc.submitNote}</div>` : ''}</div><div class="success-message" id="successMsg" style="display:none;"><div class="check-icon">✅</div><h3>${lc.successMessage}</h3><p>${lc.successSubtext}</p></div></div></div>`;
  }

  // ── INPUT RENDERING ────────────────────────────────────
  function renderInput(step, sid) {
    switch (step.input.type) {
      case 'select': return renderSelect(step, sid);
      case 'multi_select': return renderMultiSelect(step, sid);
      case 'slider_group': return renderSliders(step, sid);
      case 'toggle_group': return renderToggles(step, sid);
      default: return '';
    }
  }

  function renderSelect(step, sid) {
    const input = step.input;
    const cols = input.columns || 1;
    const colsClass = cols > 1 ? ` cols-${cols}` : '';
    let html = `<div class="option-grid${colsClass}">`;
    input.options.forEach(opt => {
      const selected = state.answers[step.id] === opt.value ? ' selected' : '';
      const tags = opt.tags ? opt.tags.map(t => `<span class="option-tag${t.highlight ? ' highlight' : ''}">${t.text}</span>`).join('') : '';
      html += `<div class="option-card${selected}" onclick="iTabs.selectOption('${step.id}','${opt.value}',${C.steps.indexOf(step)},${input.autoAdvance || false})"><div class="option-top"><span class="option-name">${opt.icon} ${opt.label}</span>${opt.priceHint ? `<span class="option-price">${opt.priceHint}</span>` : ''}</div>${opt.description ? `<div class="option-desc">${opt.description}</div>` : ''}${tags ? `<div class="option-tags">${tags}</div>` : ''}<span class="option-check">✓ Selected</span></div>`;
    });
    return html + '</div>';
  }

  function renderMultiSelect(step, sid) {
    if (!state.answers[step.id]) state.answers[step.id] = [];
    const input = step.input;
    const cols = input.columns || 1;
    const colsClass = cols > 1 ? ` cols-${cols}` : '';
    let html = `<div class="option-grid${colsClass}">`;
    input.options.forEach(opt => {
      const selected = state.answers[step.id].includes(opt.value) ? ' selected' : '';
      html += `<div class="option-card${selected}" onclick="iTabs.toggleMultiOption('${step.id}','${opt.value}',this)"><div class="option-top"><span class="option-name">${opt.icon} ${opt.label}</span>${opt.priceHint ? `<span class="option-price">${opt.priceHint}</span>` : ''}</div>${opt.description ? `<div class="option-desc">${opt.description}</div>` : ''}<span class="option-check">✓ Selected</span></div>`;
    });
    html += '</div>';
    if (input.optional) html += `<button class="tab" style="margin-top:10px;width:100%;text-align:center;" onclick="iTabs.skipStep(${C.steps.indexOf(step)})">Skip — none needed</button>`;
    return html;
  }

  function renderSliders(step, sid) {
    let html = '';
    step.input.sliders.forEach(s => {
      const current = state.sliders[s.id];
      const displayValue = current ? current.label : s.default + (s.unit || '');
      html += `<div class="slider-group"><div class="slider-label"><span>${s.label}</span><span class="slider-value" id="slider-val-${s.id}">${displayValue}</span></div><input type="range" id="slider-${s.id}" min="${s.min}" max="${s.max}" value="${s.default}" step="${s.step}" oninput="iTabs.updateSlider('${s.id}','${step.id}',${C.steps.indexOf(step)},this.value)">${s.markers ? `<div class="slider-markers">${s.markers.map(m => `<span>${m}</span>`).join('')}</div>` : ''}</div>`;
    });
    return html;
  }

  function renderToggles(step, sid) {
    return step.input.toggles.map(t => {
      const isOn = state.toggles[t.id] ? ' on' : '';
      return `<div class="toggle-row"><div class="toggle-info"><div class="toggle-name">${t.icon} ${t.label}</div><div class="toggle-cost">${t.costHint}</div></div><div class="toggle-switch${isOn}" id="toggle-${t.id}" onclick="iTabs.toggleExtra('${t.id}','${step.id}',${C.steps.indexOf(step)})"><div class="toggle-knob"></div></div></div>`;
    }).join('');
  }

  // ── HINTS ──────────────────────────────────────────────
  function renderHint(hint) {
    switch (hint.type) {
      case 'comparison_table': return renderComparisonTable(hint);
      case 'tips': return hint.tips.map(t => `<div class="tip-card"><div class="tip-title">${t.icon} ${t.title}</div><p>${t.text}</p></div>`).join('');
      case 'mixed': return hint.content.map(item => renderHintItem(item)).join('');
      case 'custom_html': return hint.content;
      default: return '';
    }
  }

  function renderComparisonTable(hint) {
    let html = '<table class="compare-table"><thead><tr>';
    hint.columns.forEach(c => { html += `<th>${c}</th>`; });
    html += '</tr></thead><tbody>';
    hint.rows.forEach(row => {
      html += '<tr>';
      row.forEach(cell => {
        const style = hint.cellStyles && hint.cellStyles[cell];
        html += `<td${style ? ` class="${style}"` : ''}>${cell}</td>`;
      });
      html += '</tr>';
    });
    return html + '</tbody></table>';
  }

  function renderHintItem(item) {
    switch (item.type) {
      case 'paragraph': return `<p style="color:var(--text-secondary);font-size:0.9rem;line-height:1.6;margin-bottom:12px;">${item.text}</p>`;
      case 'key_point': return `<div class="key-point"><div class="kp-label">${item.label}</div><p>${item.text}</p></div>`;
      case 'tip': return `<div class="tip-card"><div class="tip-title">${item.icon} ${item.title}</div><p>${item.text}</p></div>`;
      default: return '';
    }
  }

  // ── INTERACTIONS ───────────────────────────────────────
  function toggleSection(index) {
    const sid = `section-${index}`;
    const content = document.getElementById(sid + '-content');
    const btn = document.getElementById(sid + '-btn');
    const isOpen = content && content.classList.contains('show');
    document.querySelectorAll('.itab-content').forEach(c => c.classList.remove('show'));
    document.querySelectorAll('.i-button').forEach(b => b.classList.remove('active'));
    if (!isOpen && content) {
      content.classList.add('show');
      if (btn) btn.classList.add('active');
      state.openSection = sid;
      state.completedSections.add(sid);
      updateProgress();
      setTimeout(() => { document.getElementById(sid).scrollIntoView({ behavior: 'smooth', block: 'start' }); }, 100);
    } else {
      state.openSection = null;
    }
  }

  function showTab(btn, panelId) {
    const container = btn.closest('.itab-content');
    container.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    container.querySelectorAll('.tab-panel').forEach(p => p.classList.remove('show'));
    btn.classList.add('active');
    document.getElementById(panelId).classList.add('show');
  }

  function selectOption(stepId, value, stepIndex, autoAdvance) {
    state.answers[stepId] = value;
    const sid = `section-${stepIndex}`;
    const section = document.getElementById(sid);
    const step = C.steps[stepIndex];
    const cards = section.querySelectorAll(`#${sid}-input .option-card`);
    step.input.options.forEach((opt, i) => {
      if (cards[i]) cards[i].classList.toggle('selected', opt.value === value);
    });
    section.classList.add('completed');
    state.completedSections.add(sid);
    const opt = step.input.options.find(o => o.value === value);
    document.getElementById(sid + '-preview').innerHTML = `<span class="selected">✓ ${opt ? opt.label : value}</span>`;
    updateEstimate(); updateQuoteSummary(); updateProgress(); checkWarnings();
    if (autoAdvance) setTimeout(() => toggleSection(stepIndex + 1), 400);
  }

  function toggleMultiOption(stepId, value, el) {
    if (!state.answers[stepId]) state.answers[stepId] = [];
    const idx = state.answers[stepId].indexOf(value);
    if (idx > -1) { state.answers[stepId].splice(idx, 1); el.classList.remove('selected'); }
    else { state.answers[stepId].push(value); el.classList.add('selected'); }
    updateEstimate(); updateQuoteSummary();
  }

  function updateSlider(sliderId, stepId, stepIndex, rawValue) {
    const step = C.steps[stepIndex];
    const sliderConfig = step.input.sliders.find(s => s.id === sliderId);
    const raw = parseFloat(rawValue);
    if (sliderConfig.valueMap) {
      const mapped = sliderConfig.valueMap.find(v => v.value === raw);
      state.sliders[sliderId] = { raw, numeric: mapped ? mapped.numericValue : raw, label: mapped ? mapped.label : raw + (sliderConfig.unit || '') };
    } else {
      state.sliders[sliderId] = { raw, numeric: raw, label: raw + (sliderConfig.unit || '') };
    }
    document.getElementById(`slider-val-${sliderId}`).textContent = state.sliders[sliderId].label;
    const sid = `section-${stepIndex}`;
    document.getElementById(sid).classList.add('completed');
    state.completedSections.add(sid);
    const previews = step.input.sliders.map(s => { const v = state.sliders[s.id]; return s.valueMap ? v.numeric + 'm' : v.raw + (s.unit || ''); });
    document.getElementById(sid + '-preview').innerHTML = `<span class="selected">✓ ${previews.join(' × ')}</span>`;
    updateEstimate(); updateQuoteSummary(); updateProgress(); checkWarnings();
  }

  function toggleExtra(toggleId, stepId, stepIndex) {
    state.toggles[toggleId] = !state.toggles[toggleId];
    document.getElementById(`toggle-${toggleId}`).classList.toggle('on');
    const sid = `section-${stepIndex}`;
    const step = C.steps[stepIndex];
    const activeCount = step.input.toggles.filter(t => state.toggles[t.id]).length;
    if (activeCount > 0) {
      document.getElementById(sid + '-preview').innerHTML = `<span class="selected">✓ ${activeCount} extra${activeCount > 1 ? 's' : ''} added</span>`;
      document.getElementById(sid).classList.add('completed');
      state.completedSections.add(sid);
    } else {
      document.getElementById(sid + '-preview').textContent = step.preview;
      document.getElementById(sid).classList.remove('completed');
      state.completedSections.delete(sid);
    }
    updateEstimate(); updateQuoteSummary(); updateProgress();
  }

  function skipStep(stepIndex) { toggleSection(stepIndex + 1); }

  // ── PRICING ENGINE v1.1 ────────────────────────────────
  function getSliderNumeric(sliderId) { return state.sliders[sliderId] ? state.sliders[sliderId].numeric : 0; }

  function applyAdjustments(low, high, adjustments) {
    if (!adjustments) return { low, high };
    adjustments.forEach(adj => {
      const answer = state.answers[adj.source];
      if (answer !== undefined && adj.type === 'additive') {
        const val = adj.values[answer] !== undefined ? adj.values[answer] : (adj.values._default || 0);
        low += val; high += val;
      }
    });
    return { low, high };
  }

  function calculateEstimate() {
    const p = C.pricing;
    const primaryAnswer = state.answers[p.basePriceStep];
    if (!primaryAnswer || !p.basePrices[primaryAnswer]) return null;
    const base = p.basePrices[primaryAnswer];
    let low = base.low, high = base.high;

    // 1. Pre-multiplier adjustments
    const pre = applyAdjustments(low, high, p.preAdjustments);
    low = pre.low; high = pre.high;

    // 2. Multipliers (slider value_map or select_map)
    if (p.multipliers) {
      p.multipliers.forEach(m => {
        let mult = 1;
        if (m.type === 'value_map' && state.sliders[m.source]) {
          mult = m.values[getSliderNumeric(m.source)] !== undefined ? m.values[getSliderNumeric(m.source)] : 1;
        } else if (m.type === 'select_map' && state.answers[m.source] !== undefined) {
          mult = m.values[state.answers[m.source]] !== undefined ? m.values[state.answers[m.source]] : 1;
        }
        low *= mult; high *= mult;
      });
    }

    // 3. Quantity
    const quantity = p.quantitySource && state.sliders[p.quantitySource] ? state.sliders[p.quantitySource].numeric : 1;
    low = Math.round(low * quantity); high = Math.round(high * quantity);

    // 4. Post-multiplier adjustments
    const post = applyAdjustments(low, high, p.postAdjustments);
    low = post.low; high = post.high;

    // Breakdown
    const breakdown = [];
    const primaryOpt = findOption(p.basePriceStep, primaryAnswer);
    let baseLine = primaryOpt ? primaryOpt.label : primaryAnswer;
    if (p.quantitySource && state.sliders[p.quantitySource]) {
      baseLine += ` (${state.sliders[p.quantitySource].raw}${getSliderUnit(p.quantitySource)})`;
    }
    breakdown.push({ label: baseLine, low, high });

    // 5. Extras
    let runningLow = low, runningHigh = high;
    if (p.extras) {
      p.extras.forEach(extra => {
        if (!state.toggles[extra.id]) return;
        let extLow = 0, extHigh = 0;
        switch (extra.type) {
          case 'fixed': extLow = extra.low; extHigh = extra.high; break;
          case 'per_unit': extLow = Math.round(extra.lowPerUnit * quantity); extHigh = Math.round(extra.highPerUnit * quantity); break;
          case 'percentage': extLow = Math.round(runningLow * (extra.lowPercent / 100)); extHigh = Math.round(runningHigh * (extra.highPercent / 100)); break;
        }
        runningLow += extLow; runningHigh += extHigh;
        breakdown.push({ label: extra.breakdownLabel, low: extLow, high: extHigh, prefix: extra.type === 'percentage' ? '+' : '' });
      });
    }

    // 6. Minimum & rounding
    runningLow = Math.max(runningLow, p.minimumPrice || 0);
    runningHigh = Math.max(runningHigh, p.minimumPrice || 0);
    if (p.roundTo && p.roundTo > 0) {
      runningLow = Math.round(runningLow / p.roundTo) * p.roundTo;
      runningHigh = Math.round(runningHigh / p.roundTo) * p.roundTo;
    }
    return { low: runningLow, high: runningHigh, breakdown };
  }

  function findOption(stepId, value) {
    const step = C.steps.find(s => s.id === stepId);
    return step && step.input.options ? step.input.options.find(o => o.value === value) : null;
  }

  function getSliderUnit(sliderId) {
    for (const step of C.steps) {
      if (step.input.type === 'slider_group') {
        const s = step.input.sliders.find(sl => sl.id === sliderId);
        if (s) return s.unit || '';
      }
    }
    return '';
  }

  function updateEstimate() {
    const est = calculateEstimate();
    const rangeEl = document.getElementById('estRange');
    const noteEl = document.getElementById('estNote');
    const breakdownEl = document.getElementById('estBreakdown');
    const estIdx = C.steps.length;
    const previewEl = document.getElementById(`section-${estIdx}-preview`);
    if (!rangeEl) return;
    if (!est) {
      rangeEl.textContent = '—';
      noteEl.textContent = 'Complete the sections above to see your estimate';
      breakdownEl.innerHTML = '';
      if (previewEl) previewEl.textContent = C.estimate.preview;
      return;
    }
    const rangeText = `$${est.low.toLocaleString()} – $${est.high.toLocaleString()}`;
    rangeEl.textContent = rangeText;
    noteEl.textContent = C.estimate.note;
    if (C.pricing.showBreakdown && est.breakdown) {
      breakdownEl.innerHTML = est.breakdown.map(b => `<div class="breakdown-row"><span class="br-label">${b.label}</span><span class="br-value">${b.prefix || ''}$${b.low.toLocaleString()} – $${b.high.toLocaleString()}</span></div>`).join('');
    }
    if (previewEl) previewEl.innerHTML = `<span class="selected">✓ ${rangeText}</span>`;
  }

  function updateQuoteSummary() {
    const el = document.getElementById('quoteSummary');
    if (!el) return;
    let lines = [];
    C.steps.forEach(step => {
      if (step.input.type === 'select' && state.answers[step.id]) {
        const opt = findOption(step.id, state.answers[step.id]);
        lines.push(`${opt ? opt.icon : '•'} ${step.title}: <strong>${opt ? opt.label : state.answers[step.id]}</strong>`);
      }
      if (step.input.type === 'slider_group') {
        const vals = step.input.sliders.map(s => state.sliders[s.id] ? state.sliders[s.id].label : '').filter(Boolean);
        if (vals.length) lines.push(`📏 ${step.title}: <strong>${vals.join(' × ')}</strong>`);
      }
      if (step.input.type === 'toggle_group') {
        const active = step.input.toggles.filter(t => state.toggles[t.id]);
        if (active.length) lines.push(`➕ Extras: ${active.map(t => t.icon + ' ' + t.label).join(', ')}`);
      }
    });
    const est = calculateEstimate();
    if (est) lines.push(`💰 Estimate: <strong>$${est.low.toLocaleString()} – $${est.high.toLocaleString()}</strong>`);
    el.innerHTML = lines.length ? lines.join('<br>') : 'Select your options above first';
  }

  function checkWarnings() {
    const answers = state.answers;
    C.steps.forEach((step, i) => {
      if (!step.warnings) return;
      step.warnings.forEach(w => {
        const el = document.getElementById(`section-${i}-warning-${w.condition.replace(/[^a-z0-9]/gi,'')}`);
        if (!el) return;
        try { el.style.display = eval(w.condition) ? 'block' : 'none'; } catch(e) { el.style.display = 'none'; }
      });
    });
  }

  function updateProgress() {
    const total = C.steps.length + (C.estimate ? 1 : 0) + (C.leadCapture && C.leadCapture.enabled ? 1 : 0);
    const completed = state.completedSections.size;
    const fillEl = document.getElementById('progressFill');
    const textEl = document.getElementById('progressText');
    if (fillEl) fillEl.style.width = (completed / total) * 100 + '%';
    if (textEl) textEl.textContent = `${completed} of ${total}`;
  }

  // ── LEAD SUBMISSION ────────────────────────────────────
  async function submitLead() {
    const lc = C.leadCapture;
    const formData = {};
    let missing = false;
    lc.fields.forEach(f => {
      const el = document.getElementById(`form-${f.id}`);
      formData[f.id] = el ? el.value.trim() : '';
      if (f.required && !formData[f.id]) missing = true;
    });
    if (missing) { alert('Just need the required fields filled in 👍'); return; }
    const btn = document.getElementById('submitBtn');
    btn.textContent = 'Sending...'; btn.disabled = true;

    let selections = '';
    C.steps.forEach(step => {
      if (step.input.type === 'select' && state.answers[step.id]) {
        const opt = findOption(step.id, state.answers[step.id]);
        selections += `${step.title}: ${opt ? opt.label : state.answers[step.id]}\n`;
      }
      if (step.input.type === 'slider_group') {
        selections += step.input.sliders.map(s => `${s.label}: ${state.sliders[s.id] ? state.sliders[s.id].label : ''}`).join(', ') + '\n';
      }
      if (step.input.type === 'toggle_group') {
        const active = step.input.toggles.filter(t => state.toggles[t.id]).map(t => t.label);
        if (active.length) selections += `Extras: ${active.join(', ')}\n`;
      }
    });
    const est = calculateEstimate();
    const estText = est ? `$${est.low.toLocaleString()} – $${est.high.toLocaleString()}` : 'Not calculated';

    try {
      if (lc.delivery.method === 'web3forms') {
        await fetch('https://api.web3forms.com/submit', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            access_key: lc.delivery.web3formsKey,
            subject: lc.delivery.emailSubject.replace('{business.name}', C.business.name),
            from_name: `${C.business.name} Quote Widget`,
            to: lc.delivery.notifyEmail,
            message: `NEW QUOTE ENQUIRY\n==================\n${Object.entries(formData).map(([k,v]) => `${k}: ${v}`).join('\n')}\n\nSELECTIONS\n==================\n${selections}\nESTIMATE SHOWN: ${estText}`.trim(),
            ...formData, estimate_range: estText, selections_summary: selections,
          }),
        });
      }
    } catch (err) { console.error('iTabs submit error:', err); }

    document.getElementById('leadFormContainer').style.display = 'none';
    document.getElementById('successMsg').style.display = 'block';
    const idx = C.steps.length + (C.estimate ? 1 : 0);
    const sid = `section-${idx}`;
    document.getElementById(sid).classList.add('completed');
    state.completedSections.add(sid);
    document.getElementById(sid + '-preview').innerHTML = '<span class="selected">✓ Sent!</span>';
    updateProgress();
  }

  function getPreview(step) {
    if (step.input.type === 'select' && state.answers[step.id]) {
      const opt = step.input.options.find(o => o.value === state.answers[step.id]);
      return `<span class="selected">✓ ${opt ? opt.label : state.answers[step.id]}</span>`;
    }
    return step.preview;
  }

  // ── PUBLIC API (for onclick handlers) ──────────────────
  window.iTabs = {
    toggleSection, showTab, selectOption, toggleMultiOption,
    updateSlider, toggleExtra, skipStep, submitLead,
  };

  // ── GO ─────────────────────────────────────────────────
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
